// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // In production, Supabase's Vercel integration sets POSTGRES_URL_NON_POOLING
    // (a direct, non-pooled connection) — migrations need this rather than the
    // pooled POSTGRES_PRISMA_URL, since pgbouncer's transaction-pooling mode
    // doesn't reliably support the operations migrations perform. Locally,
    // there's just one Postgres instance, so DATABASE_URL covers both.
    url: process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["DATABASE_URL"],
  },
});
